version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./docker/localstack/volume:/var/lib/localstack"
      - "./docker/localstack/init:/docker-entrypoint-initaws.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
